#
# EcoMobs
# by Auxilor
#

discover-recipes: true

custom-spawning:
  # The spawn rate is the number of ticks to wait between trying to spawn a mob.
  # 20 ticks = 1 second; the higher the number, the less often mobs will spawn.
  spawn-rate: 5

  # The radius to generate spawn points for around the player
  radius-around-player: 32

  # The max amount of spawn points to generate per player
  max-points-per-player: 8

  # The max amount of attempts to generate a spawn point per player
  max-attempts: 64